name: Run emulator instrumented tests
description: Boot an API 34 emulator and run connectedDebugAndroidTest.

runs:
  using: composite
  steps:
    - uses: reactivecircus/android-emulator-runner@a421e43855164a8197daf9d8d40fe71c6996bb0d # v2.38.0
      with:
        api-level: 34
        target: google_apis
        arch: x86_64
        profile: pixel_5
        disable-animations: true
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: |
          adb shell settings put global verifier_verify_adb_installs 0
          adb shell settings put global package_verifier_enable 0
          adb shell wm dismiss-keyguard || true
          ./gradlew connectedDebugAndroidTest --stacktrace
